import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <div className={styles.container_principal}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container_texto}>
        <h1>Hello World</h1>
        <p>Primeiro teste com tags HTML no react</p>
        <p className={styles.autor}>Criado por Antonio Venturim - Multivix</p>
      </div>
    </div>
  );
}
